import streamlit as st 
from dotenv import load_dotenv
import os 
import openai
from diffusers import StableDiffusionPipeline
import torch

load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")


#function to generate AI based images using OpenAI Dall-E
# def generate_images_using_openai(text):
#     response = openai.Image.create(prompt= text, n=1, size="512x512")
#     image_url = response['data'][0]['url']
#     return image_url

#function to generate AI based images using Huggingface Diffusers
def generate_images_using_huggingface_diffusers(text):
    pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
    pipe = pipe.to("cuda")
    prompt = text
    image = pipe(prompt).images[0] 
    return image

# Function to generate content using GPT-4
def generate_content(prompt):
    response = openai.Completion.create(
        engine="gpt-4",
        prompt=prompt,
        max_tokens=50
    )
    content = response.choices[0].message['content'].strip()
    return content

#Streamlit Code
choice = st.sidebar.selectbox("Select your choice", ["Home", "DALL-E", "Huggingface Diffusers","Content Creation"])

if choice == "Home":
    st.title("AI Image and Content Generation App")
    with st.expander("About the App"):
        st.write("This is a simple image generation app that uses AI to generates images from text prompt.")

elif choice == "DALL-E":
    st.subheader("Image generation using Open AI's DALL-E")
    input_prompt = st.text_input("Enter your text prompt")
    if input_prompt is not None:
        if st.button("Generate Image"):
            image_url = generate_images_using_openai(input_prompt)
            st.image(image_url, caption="Generated by DALL-E")

elif choice == "Huggingface Diffusers":
    st.subheader("Image generation using Huggingface Diffusers")
    input_prompt = st.text_input("Enter your text prompt")
    if input_prompt is not None:
        if st.button("Generate Image"):
            image_output = generate_images_using_huggingface_diffusers(input_prompt)
            st.info("Generating image.....")
            st.success("Image Generated Successfully")
            st.image(image_output, caption="Generated by Huggingface Diffusers")

elif choice == "Content Creation":
    st.subheader("Chat with GPT-4 and Image Generation")
    # Initialize chat history
    if "messages" not in st.session_state:
        st.session_state.messages = []

    # Function to generate response from GPT-4
    def generate_gpt_response(prompt):
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message['content'].strip()
    
    # Function to generate images using OpenAI DALL-E
    def generate_image(prompt):
        response = openai.Image.create(
            prompt=prompt,
            n=1,
            size="512x512"
        )
        image_url = response['data'][0]['url']
        return image_url

    # Display chat messages from history on app rerun
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            if "image" in message:
                st.image(message["image"], caption=message["content"])
            else:
                st.markdown(message["content"])

    # React to user input
    if prompt := st.chat_input("What is up?"):
        # Display user message in chat message container
        st.chat_message("user").markdown(prompt)
        # Add user message to chat history
        st.session_state.messages.append({"role": "user", "content": prompt})

        # Generate GPT response
        # response = generate_gpt_response(prompt)
        if "image" in prompt.lower():
            response = generate_image(prompt)
            st.session_state.messages.append({"role": "assistant", "content": prompt, "image": response})
        else:
            response = generate_gpt_response(prompt)
            st.session_state.messages.append({"role": "assistant", "content": response})

        
        # Display assistant response in chat message container
        with st.chat_message("assistant"):
            # st.markdown(response)
            if "image" in prompt.lower():
                st.image(response, caption=prompt)
            else:
                st.markdown(response)
        # Add assistant response to chat history
        st.session_state.messages.append({"role": "assistant", "content": response})
